'use strict';

const RULESET_VERSION = '2026-09-22.1';

const STATUSES = Object.freeze({
    AVAILABLE: 'AVAILABLE',
    POA: 'POA',
    UNAVAILABLE: 'UNAVAILABLE',
    HIDDEN: 'HIDDEN',
});

const DECORATION_METHODS = Object.freeze({
    embroidery: { label: 'Embroidery', type: 'stitch' },
    dtf: { label: 'DTF Print', type: 'print' },
    screen_print: { label: 'Screen Print', type: 'print', customerFacing: false },
});

const GLOBAL_CAPABILITIES = Object.freeze({
    embroidery: STATUSES.AVAILABLE,
    dtf: STATUSES.AVAILABLE,
    screen_print: STATUSES.HIDDEN,
});

const A = STATUSES.AVAILABLE;
const P = STATUSES.POA;
const U = STATUSES.UNAVAILABLE;

function capabilities(dtf, screenPrint, embroidery) {
    return Object.freeze({ dtf, screen_print: screenPrint, embroidery });
}

const PRODUCT_CAPABILITIES = Object.freeze({
    cotton_tshirt: capabilities(A, A, P),
    heavy_premium_tshirt: capabilities(A, A, A),
    polyester_tshirt: capabilities(A, P, P),
    performance_tshirt: capabilities(A, P, P),
    hi_vis_tshirt: capabilities(A, P, P),
    long_sleeve_tshirt: capabilities(A, A, A),
    cotton_polo: capabilities(A, A, A),
    polyester_polo: capabilities(A, P, A),
    performance_polo: capabilities(A, P, A),
    long_sleeve_polo: capabilities(A, A, A),
    work_shirt: capabilities(A, P, A),
    formal_shirt: capabilities(P, U, A),
    oxford_shirt: capabilities(P, U, A),
    blouse: capabilities(P, U, A),
    tunic: capabilities(A, P, A),
    scrub_top: capabilities(A, P, A),
    scrub_trousers: capabilities(P, U, P),
    lab_coat: capabilities(A, P, A),
    beauty_tunic: capabilities(A, P, A),
    crewneck_sweatshirt: capabilities(A, A, A),
    pullover_hoodie: capabilities(A, A, A),
    zip_hoodie: capabilities(A, A, A),
    technical_sweatshirt: capabilities(A, P, A),
    quarter_zip_sweatshirt: capabilities(A, P, A),
    cotton_knitwear: capabilities(P, U, A),
    wool_knitwear: capabilities(U, U, P),
    cardigan: capabilities(P, U, A),
    fleece: capabilities(P, U, A),
    microfleece: capabilities(P, U, A),
    zip_fleece: capabilities(P, U, A),
    softshell_jacket: capabilities(A, U, A),
    softshell_bodywarmer: capabilities(A, U, A),
    padded_jacket: capabilities(P, U, A),
    waterproof_jacket: capabilities(P, U, A),
    windbreaker: capabilities(A, P, A),
    technical_jacket: capabilities(P, U, A),
    bomber_jacket: capabilities(A, P, A),
    parka: capabilities(P, U, A),
    padded_bodywarmer: capabilities(P, U, A),
    bodywarmer: capabilities(A, U, A),
    hi_vis_vest: capabilities(A, A, P),
    hi_vis_waistcoat: capabilities(A, A, P),
    hi_vis_polo: capabilities(A, P, A),
    hi_vis_sweatshirt: capabilities(A, A, A),
    hi_vis_hoodie: capabilities(A, A, A),
    hi_vis_fleece: capabilities(P, U, A),
    hi_vis_softshell: capabilities(A, U, A),
    hi_vis_jacket: capabilities(P, U, A),
    hi_vis_bomber: capabilities(P, U, A),
    hi_vis_trousers: capabilities(P, U, P),
    coverall: capabilities(A, P, A),
    boiler_suit: capabilities(A, P, A),
    bib_and_brace: capabilities(A, P, A),
    workwear_trousers: capabilities(P, U, A),
    cargo_trousers: capabilities(P, U, A),
    workwear_shorts: capabilities(P, U, A),
    chef_jacket: capabilities(A, P, A),
    chef_trousers: capabilities(P, U, P),
    chef_hat: capabilities(P, U, A),
    bib_apron: capabilities(A, A, A),
    waist_apron: capabilities(A, A, A),
    tabard: capabilities(A, A, A),
    hospitality_waistcoat: capabilities(P, U, A),
    rugby_shirt: capabilities(A, A, A),
    football_shirt: capabilities(A, P, P),
    basketball_jersey: capabilities(A, P, U),
    sports_vest: capabilities(A, P, U),
    tracksuit_top: capabilities(A, P, A),
    tracksuit_trousers: capabilities(P, U, P),
    leggings: capabilities(P, U, U),
    sports_shorts: capabilities(P, P, U),
    running_jacket: capabilities(A, P, P),
    school_jumper: capabilities(A, A, A),
    school_cardigan: capabilities(P, U, A),
    school_blazer: capabilities(P, U, A),
    school_polo: capabilities(A, A, A),
    school_pe_kit: capabilities(A, A, P),
    leavers_hoodie: capabilities(A, A, A),
    baby_bodysuit: capabilities(A, A, U),
    kids_tshirt: capabilities(A, A, P),
    kids_hoodie: capabilities(A, A, A),
    baseball_cap: capabilities(P, U, A),
    trucker_cap: capabilities(P, U, A),
    snapback: capabilities(P, U, A),
    beanie: capabilities(U, U, A),
    bobble_hat: capabilities(U, U, A),
    bucket_hat: capabilities(P, P, A),
    visor: capabilities(P, U, A),
    balaclava: capabilities(U, U, P),
    scarf: capabilities(P, U, A),
    gloves: capabilities(U, U, P),
    tie: capabilities(P, U, A),
    backpack: capabilities(A, P, A),
    drawstring_bag: capabilities(A, A, A),
    cotton_tote_bag: capabilities(A, A, A),
    canvas_bag: capabilities(A, A, A),
    laptop_bag: capabilities(P, U, A),
    messenger_bag: capabilities(P, U, A),
    sports_holdall: capabilities(A, P, A),
    kit_bag: capabilities(A, P, A),
    cooler_bag: capabilities(P, U, A),
    tool_bag: capabilities(P, U, A),
    umbrella: capabilities(P, A, U),
    towel: capabilities(P, U, A),
    blanket: capabilities(P, U, A),
    patch_badge: capabilities(P, U, A),
    safety_helmet: capabilities(P, U, U),
    hard_hat: capabilities(P, U, U),
    safety_footwear: capabilities(U, U, P),
    socks: capabilities(P, U, P),
});

const POSITION_CAPABILITIES = Object.freeze({
    left_chest: capabilities(A, A, A),
    right_chest: capabilities(A, A, A),
    centre_chest: capabilities(A, A, A),
    large_front: capabilities(A, A, P),
    upper_back: capabilities(A, A, A),
    large_back: capabilities(A, A, P),
    left_sleeve: capabilities(A, A, A),
    right_sleeve: capabilities(A, A, A),
    back_neck: capabilities(A, A, A),
    lower_front: capabilities(A, A, P),
    lower_back: capabilities(A, A, P),
    trouser_thigh: capabilities(A, P, A),
    trouser_leg: capabilities(A, P, P),
    cap_front: capabilities(P, U, A),
    cap_side: capabilities(P, U, A),
    cap_back: capabilities(P, U, A),
    bag_front: capabilities(A, A, A),
    apron_front: capabilities(A, A, A),
});

const FALLBACK_PRIORITY = Object.freeze({
    embroidery: Object.freeze(['dtf', 'screen_print']),
    screen_print: Object.freeze(['dtf', 'embroidery']),
    dtf: Object.freeze(['screen_print', 'embroidery']),
});

const SKU_OVERRIDES = Object.freeze({});

module.exports = {
    RULESET_VERSION,
    STATUSES,
    DECORATION_METHODS,
    GLOBAL_CAPABILITIES,
    PRODUCT_CAPABILITIES,
    POSITION_CAPABILITIES,
    FALLBACK_PRIORITY,
    SKU_OVERRIDES,
};
